[2025-07-28T14:09:09.331+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: github_events_elt_pipeline.extract_and_load_to_staging manual__2025-07-27T19:40:46.201979+00:00 [queued]>
[2025-07-28T14:09:09.353+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: github_events_elt_pipeline.extract_and_load_to_staging manual__2025-07-27T19:40:46.201979+00:00 [queued]>
[2025-07-28T14:09:09.355+0000] {taskinstance.py:2193} INFO - Starting attempt 15 of 15
[2025-07-28T14:09:09.389+0000] {taskinstance.py:2217} INFO - Executing <Task(KubernetesPodOperator): extract_and_load_to_staging> on 2025-07-27 19:40:46.201979+00:00
[2025-07-28T14:09:09.403+0000] {standard_task_runner.py:60} INFO - Started process 184 to run task
[2025-07-28T14:09:09.413+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'github_events_elt_pipeline', 'extract_and_load_to_staging', 'manual__2025-07-27T19:40:46.201979+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/github_events_elt_pipeline.py', '--cfg-path', '/tmp/tmpxfdef9gv']
[2025-07-28T14:09:09.422+0000] {standard_task_runner.py:88} INFO - Job 62: Subtask extract_and_load_to_staging
[2025-07-28T14:09:09.475+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-28T14:09:09.591+0000] {task_command.py:423} INFO - Running <TaskInstance: github_events_elt_pipeline.extract_and_load_to_staging manual__2025-07-27T19:40:46.201979+00:00 [running]> on host 27ea3cb9cc38
[2025-07-28T14:09:09.881+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='github_events_elt_pipeline' AIRFLOW_CTX_TASK_ID='extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-07-27T19:40:46.201979+00:00' AIRFLOW_CTX_TRY_NUMBER='15' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-27T19:40:46.201979+00:00'
[2025-07-28T14:09:09.914+0000] {pod.py:1076} INFO - Building pod kafka-consumer-pod-o1899xvb with labels: {'dag_id': 'github_events_elt_pipeline', 'task_id': 'extract_and_load_to_staging', 'run_id': 'manual__2025-07-27T194046.2019790000-fccb62a8d', 'kubernetes_pod_operator': 'True', 'try_number': '15'}
[2025-07-28T14:09:10.059+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:09:10.116+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:09:10.297+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:09:10.343+0000] {pod.py:535} INFO - Found matching pod kafka-consumer-pod-o1899xvb with labels {'airflow_kpo_in_cluster': 'False', 'airflow_version': '2.8.4', 'dag_id': 'github_events_elt_pipeline', 'kubernetes_pod_operator': 'True', 'run_id': 'manual__2025-07-27T194046.2019790000-fccb62a8d', 'task_id': 'extract_and_load_to_staging', 'try_number': '15'}
[2025-07-28T14:09:10.346+0000] {pod.py:536} INFO - `try_number` of task_instance: 15
[2025-07-28T14:09:10.348+0000] {pod.py:537} INFO - `try_number` of pod: 15
[2025-07-28T14:09:10.353+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:09:10.398+0000] {pod_manager.py:374} WARNING - Pod not yet started: kafka-consumer-pod-o1899xvb
[2025-07-28T14:09:15.414+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:09:15.547+0000] {pod_manager.py:374} WARNING - Pod not yet started: kafka-consumer-pod-o1899xvb
[2025-07-28T14:09:20.564+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:09:20.701+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:09:20.822+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:09:21.110+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:14:21.339+0000] {pod_manager.py:484} INFO - [base] None
[2025-07-28T14:14:21.353+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:14:21.366+0000] {pod_manager.py:512} WARNING - Pod kafka-consumer-pod-o1899xvb log read interrupted but container base still running
[2025-07-28T14:14:22.369+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:14:22.394+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:19:22.464+0000] {pod_manager.py:484} INFO - [base] None
[2025-07-28T14:19:22.489+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:19:22.512+0000] {pod_manager.py:512} WARNING - Pod kafka-consumer-pod-o1899xvb log read interrupted but container base still running
[2025-07-28T14:19:23.517+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:19:23.552+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:24:23.655+0000] {pod_manager.py:484} INFO - [base] None
[2025-07-28T14:24:23.670+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:24:23.682+0000] {pod_manager.py:512} WARNING - Pod kafka-consumer-pod-o1899xvb log read interrupted but container base still running
[2025-07-28T14:24:24.686+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:24:24.709+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:29:24.778+0000] {pod_manager.py:484} INFO - [base] None
[2025-07-28T14:29:24.801+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:29:24.818+0000] {pod_manager.py:512} WARNING - Pod kafka-consumer-pod-o1899xvb log read interrupted but container base still running
[2025-07-28T14:29:25.822+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:29:25.846+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:34:25.924+0000] {pod_manager.py:484} INFO - [base] None
[2025-07-28T14:34:25.940+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:34:25.954+0000] {pod_manager.py:512} WARNING - Pod kafka-consumer-pod-o1899xvb log read interrupted but container base still running
[2025-07-28T14:34:26.958+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:34:26.990+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:39:27.044+0000] {pod_manager.py:484} INFO - [base] None
[2025-07-28T14:39:27.081+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:39:27.109+0000] {pod_manager.py:512} WARNING - Pod kafka-consumer-pod-o1899xvb log read interrupted but container base still running
[2025-07-28T14:39:28.114+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:39:28.173+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:44:17.596+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-07-28T14:44:17.599+0000] {process_utils.py:131} INFO - Sending 15 to group 184. PIDs of all processes in the group: [184]
[2025-07-28T14:44:17.600+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 184
[2025-07-28T14:44:17.601+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-28T14:44:17.621+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'host.docker.internal'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-07-28T14:44:17.648+0000] {pod_manager.py:484} INFO - [base] None
[2025-07-28T14:44:17.693+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=184, status='terminated', exitcode=0, started='14:09:08') (184) terminated with exit code 0
